C = str(input())
C = C.replace("c=", "a")
C = C.replace("c-", "a")
C = C.replace("dz=", "a")
C = C.replace("d-", "a")
C = C.replace("lj", "a")
C = C.replace("nj", "a")
C = C.replace("s=", "a")
C = C.replace("z=", "a")
print(len(C))
